thread1:thread1.c
	cc -D_REENTRANT thread1.c -o thread1 -lpthread
	#gcc -D_REENTRANT -I/usr/include/nptl thread1.c -o thread1 -L/usr/lib/nptl -lpthread -g

thread2:thread2.c
	cc -D_REENTRANT thread2.c -o thread2 -lpthread
